POST http://localhost:3333/events
Content-Type: application/json


{
    "title": "Novo Evento 2024",
    "details": "Evento Teste",
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/f8b263e9-9e3b-4839-b63c-acfb925ab1b8/attendees
Content-Type: application/json


{
    "name": "Wener Rodrigo",
    "email": "wener@2022.com.br"
}


###
GET http://localhost:3333/events/f8b263e9-9e3b-4839-b63c-acfb925ab1b8


###
GET http://localhost:3333/attendees/4/badge


###
GET http://localhost:3333/attendees/4/check-in


######
GET http://localhost:3333/events/f8b263e9-9e3b-4839-b63c-acfb925ab1b8/attendees?query=joel
